repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
    - id: ruff-format
      args: [., --check]
    - id: ruff-format
      args: [.]
    - id: ruff
      args: [., --fix, --exit-non-zero-on-fix, --show-fixes]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.1
    hooks:
      - id: mypy
