name: Test

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Lint
        run: mise lint

  test:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.14"
          - "3.13"
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
          - "3.8"
          - "pypy3.8"
          - "pypy3.9"
          - "pypy3.10"
          - "pypy3.11"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "${{ matrix.python-version }}"
    - name: Install dependencies
      run: python -m pip install coverage tox
    - name: Test
      run: |
        tox_factor="${{ matrix.python-version }}"
        tox_factor="${tox_factor//./}"
        tox_factor="${tox_factor/#3/py3}"
        tox run -f "$tox_factor" --skip-missing-interpreters true
        coverage xml -o ./coverage.xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: false
        files: ./coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
