name: Test

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install pre-commit
        run: python -m pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files

  test:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.13"
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
          - "3.8"
          - "pypy3.8"
          - "pypy3.9"
          - "pypy3.10"
          - "pypy3.11"
        pytest-version:
          - "pytest<8"
          - "pytest<9"
          - "pytest"
          - "git+https://github.com/pytest-dev/pytest.git@main"
        exclude:
          - python-version: "3.8"
            pytest-version: "git+https://github.com/pytest-dev/pytest.git@main"
          - python-version: "3.9"
            pytest-version: "git+https://github.com/pytest-dev/pytest.git@main"
          - python-version: "pypy3.8"
            pytest-version: "git+https://github.com/pytest-dev/pytest.git@main"
          - python-version: "pypy3.9"
            pytest-version: "git+https://github.com/pytest-dev/pytest.git@main"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "${{ matrix.python-version }}"
    - name: Install dependencies
      run: python -m pip install tox "${{ matrix.pytest-version }}" pytest-cov .
    - name: Test
      run: |
        coverage run --branch --source=pytest_unordered -m pytest tests/
        coverage xml -o ./coverage.xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: false
        files: ./coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
